<a href="https://colab.research.google.com/github/Zoya-Haris/Machine-Learning/blob/main/DiabeticPrediction_Knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/diabetes.csv')

In [ ]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
df.size

6912

In [ ]:
df.shape

(768, 9)

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [ ]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
df1 = df.groupby('Outcome')['Outcome'].count()
df1

Outcome
0    500
1    268
Name: Outcome, dtype: int64

In [ ]:
x = df.drop('Outcome', axis=1)
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [ ]:
y = df[['Outcome']]
y

Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30)
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
216            5      109             62             41      129  35.8   
334            1       95             60             18       58  23.9   
205            5      111             72             28        0  23.9   
420            1      119             88             41      170  45.3   
436           12      140             85             33        0  37.4   
..           ...      ...            ...            ...      ...   ...   
760            2       88             58             26       16  28.4   
552            6      114             88              0        0  27.8   
393            4      116             72             12       87  22.1   
422            0      102             64             46       78  40.6   
97             1       71             48             18       76  20.4   

     DiabetesPedigreeFunction  Age  
216                     0.514   25  
334                     0.260   22  
205                     0.407   27  
420                     0.507   26  
436                     0.244   41  
..                        ...  ...  
760                     0.766   22  
552                     0.247   66  
393                     0.463   37  
422                     0.496   21  
97                      0.323   22  

[537 rows x 8 columns]

In [ ]:
x_train.shape,x_test.shape

((537, 8), (231, 8))

In [ ]:
y_train.shape, y_test.shape

((537, 1), (231, 1))

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(x_train)

StandardScaler()

In [ ]:
x_train = ss.transform(x_train)
x_test = ss.transform(x_test)

In [ ]:
x_train

array([[ 0.3559105 , -0.36760997, -0.3675582 , ...,  0.48929171,
         0.17863516, -0.71693538],
       [-0.87318234, -0.82945686, -0.46818463, ..., -0.98857415,
        -0.63522943, -0.96473262],
       [ 0.3559105 , -0.30163185,  0.13557398, ..., -0.98857415,
        -0.16421331, -0.55173723],
       ...,
       [ 0.04863729, -0.13668653,  0.13557398, ..., -1.21211689,
         0.0152214 ,  0.27425355],
       [-1.18045555, -0.59853342, -0.26693176, ...,  1.08540567,
         0.12095971, -1.04733169],
       [-0.87318234, -1.62119438, -1.07194324, ..., -1.42324059,
        -0.43336538, -0.96473262]])

In [ ]:
x_test

array([[ 0.04863729,  0.78700724, -0.56881107, ..., -0.29310787,
        -0.54871627,  0.27425355],
       [-0.56590913, -1.22532562, -0.16630533, ...,  0.04220624,
         0.1241639 , -0.96473262],
       [-0.56590913, -1.72016157, -0.3675582 , ..., -1.46049771,
        -0.644842  , -0.88213354],
       ...,
       [ 0.6631837 ,  0.78700724,  0.13557398, ...,  0.25332993,
        -0.65125039,  0.52205078],
       [-0.56590913, -0.92842405,  0.33682685, ..., -0.95131703,
         3.97239764, -0.46913815],
       [ 1.58500333, -0.00473028,  0.13557398, ..., -1.37356442,
         0.88035305,  1.1828434 ]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0])

In [ ]:
knn.predict([[5,140,65,30,0,30.6,0.32,25]])

array([1])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred,y_test)
cm

array([[125,  31],
       [ 26,  49]])

In [ ]:
score = accuracy_score(y_pred,y_test)
score

0.7532467532467533